server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/user-request-db
    driver-class-name: org.postgresql.Driver
    username: usr
    password: pwd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.show_sql: true
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
    open-in-view: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  expiration:
    time: 2000000
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

logging:
  level:
    org.springframework.security: DEBUG